spring.application.name=OrchestrationEngine
server.port=6002

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.data.mongodb.uri=mongodb://localhost:27017/orc_db


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=orc_group