spring.application.name=OrchestrationEngine
server.port=6002

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

aws.dynamodb.region=ap-south-1
aws.dynamodb.endpoint=https://dynamodb.ap-south-1.amazonaws.com


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=orc_group