#!/usr/bin/env python3
"""Entry point for the CloudCostOps audit ML Kafka service."""

import argparse
import json
import sys

from label_generator import generate_cloud_metric_sample, derive_audit_labels
from predictor import build_audit_event, predict_audit_metrics


def cmd_train(_args):
    from train import train_model

    train_model()
    return 0


def cmd_predict(args):
    with open(args.file, encoding="utf-8") as handle:
        payload = json.load(handle)
    audit = build_audit_event(payload)
    print(json.dumps(audit, indent=2))
    return 0


def cmd_demo(_args):
    import random

    sample = generate_cloud_metric_sample(random.Random(7))
    predicted = predict_audit_metrics(sample)
    expected = derive_audit_labels(sample, random.Random(7))

    print("=== Input (cloud_metrics) ===")
    print(json.dumps(sample, indent=2))
    print("\n=== ML Prediction (cloud_audit_metric) ===")
    print(json.dumps(predicted, indent=2))
    print("\n=== Formula baseline (training labels) ===")
    print(json.dumps(expected, indent=2))
    return 0


def cmd_serve(_args):
    from kafka_bridge import run_bridge

    run_bridge()
    return 0


def cmd_seed(_args):
    """Publish only the 120 records from seed_records.json to Kafka.

    seed_records.json is generated by generate_seed_json.py (Amazon only,
    3 months x 40 records). No other records are processed.
    The audit-ml-service (serve mode) must be running to consume them.
    """
    import logging
    import time
    from pathlib import Path
    from kafka import KafkaProducer
    from config import INPUT_TOPIC, KAFKA_BOOTSTRAP, PUBLISH_DELAY_SECONDS

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
    )
    log = logging.getLogger("audit-ml-seed")

    seed_file = Path(__file__).resolve().parent.parent / "seed_records.json"
    if not seed_file.exists():
        print(f"ERROR: {seed_file} not found. Run generate_seed_json.py first.")
        return 1

    with open(seed_file, encoding="utf-8") as f:
        events = json.load(f)

    print(f"Publishing {len(events)} records from {seed_file.name} to Kafka...")

    try:
        producer = KafkaProducer(
            bootstrap_servers=KAFKA_BOOTSTRAP.split(","),
            value_serializer=lambda v: json.dumps(v).encode("utf-8"),
            acks="all",
            retries=3,
        )
    except Exception as exc:
        log.error("Kafka broker unavailable: %s", exc)
        return 1

    published = 0
    for event in events:
        producer.send(INPUT_TOPIC, value=event)
        producer.flush()
        published += 1
        log.info(
            "[%d/%d] eventId=%-25s  company=%-8s  agent=%s",
            published, len(events),
            event["eventId"],
            event["company"]["companyName"],
            event["agent"]["agentId"],
        )
        if PUBLISH_DELAY_SECONDS > 0:
            time.sleep(PUBLISH_DELAY_SECONDS)

    producer.close()
    if published == len(events):
        print(f"Done — {published} events published. Audit metrics will appear shortly via the serve pipeline.")
        return 0
    else:
        print(f"Warning: only {published}/{len(events)} events published.")
        return 1


def main():
    parser = argparse.ArgumentParser(description="CloudCostOps Audit ML Service")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("train", help="Train the audit metric model")
    sub.add_parser("serve", help="Run Kafka consumer/producer bridge")
    sub.add_parser("demo", help="Run a local prediction demo")
    sub.add_parser("seed", help="Publish static cloud_metrics events to Kafka (requires serve to be running)")

    predict_parser = sub.add_parser("predict", help="Predict audit metrics from a JSON file")
    predict_parser.add_argument("file", help="Path to cloud_metrics JSON file")

    args = parser.parse_args()
    handlers = {
        "train": cmd_train,
        "serve": cmd_serve,
        "demo": cmd_demo,
        "predict": cmd_predict,
        "seed": cmd_seed,
    }
    return handlers[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
